### PR TITLE
file amended to remove shadows/duplicates

### PR DESCRIPTION
**Pull request by SteveWorswick**
See https://gitlab.com/pandorabots/pb/issues/987 for details of amendments

### CODE REVIEW

**Review by pandorabots-admin — COMMENTED** [review]
["%27", "'"],["%3f", "?"]  seems to be missing, is there a reason why?

**Comment by SteveWorswick** [comment]
["%27", "'"],["%3f", "?"] both appeared twice in the file. I removed the duplicates. They still appear but are further down the file.

**Review by pandorabots-admin — COMMENTED** [review]
Can you confirm? I looked down the file in "view changes" and didn't see them.

**Comment by SteveWorswick** [comment]
They are on lines 14 and 21
https://github.com/pandorabots/rosie/blob/SteveWorswick-patch-1/lib/substitutions/normal.substitution

**Review by pandorabots-admin — APPROVED** [review]
Great! Up the line!

**Comment by pandorabots-admin** [comment]
Removed duplicates and fixed violation of rules for longer substitutions (must come before shorter ones).

**Pull request merged**
